name: Build Godot Project

on:
  # push:
  #   branches: [ 'main' ]
  workflow_dispatch: {}

jobs:
  export_web:
    name: Export
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Export Game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v5.2.1
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.1.1/Godot_v4.1.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: false
          use_preset_export_path: true
          export_debug: false
      - name: Download compo version
        uses: robinraju/release-downloader@v1.5
        with: 
          tag: "v0"
          fileName: "compo-initial-build.zip"
          out-file-path: "releases"
      - name: repack bundle
        run: |
          ls -la
          mkdir -p ./final-bundle/jam
          mkdir -p ./final-bundle/postjam
          find ./builds
          pushd ./builds/html
          find . -type f | xargs -L1 basename | xargs -L1 -I {} cp {} ../../final-bundle/postjam
          popd
          unzip ./releases/compo-initial-build.zip -d ./final-bundle/jam
          cp ./launcher.html ./final-bundle/index.html
          cp ./fonts/PixelOperatorMono.ttf ./final-bundle/.
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./final-bundle
          itchUsername: badcop
          itchGameId: dreams
          buildChannel: html
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./builds/windows/window.zip
          itchUsername: badcop
          itchGameId: dreams
          buildChannel: windows
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./builds/macos/macos.zip
          itchUsername: badcop
          itchGameId: dreams
          buildChannel: macos
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./builds/linux/linux.zip
          itchUsername: badcop
          itchGameId: dreams
          buildChannel: linux
